name: Kyle McNally
markdown: redcarpet
pygments: true
timezone: America/New_York
lsi: true
url: http://www.kmcnally.net
author: Kyle McNally
email: kyle@kmcnally.net
permalink: pretty
redcarpet:
 extensions: ['tables','autolink']
theme: jekyll-theme-cayman